# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf8eb626cb37fd430c72a7e662c8e3c935452ae01c0d80ce69d485ca34cf6bb655c9ceb446bb61466f8f6f6974494983187268fea14285a46ab67389ea8dee2e

test:
  secret_key_base: ed88c46e7b1141945081c0ba61bf66fa0a820f5fa959a797a9135a48efd31cf924b9a9a9ec3654368f3170e8a9f82cdcf55f7fe021b2cfc5a4bf1db2e7b67444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
